title: Run Expo Application Services (EAS) build
summary: Runs a build on Expo Application Services (EAS).

website: https://github.com/bitrise-steplib/bitrise-step-run-eas-build
source_code_url: https://github.com/bitrise-steplib/bitrise-step-run-eas-build
support_url: https://github.com/bitrise-steplib/bitrise-step-run-eas-build/issues

project_type_tags:
- react-native

type_tags:
  - build

toolkit:
  go:
    package_name: github.com/bitrise-steplib/bitrise-step-run-eas-build

inputs:
- access_token:
  opts:
    title: Personal Access Token
    summary: Expo Personal Access Token
    is_sensitive: true
    is_required: true

- platform: all
  opts:
    title: Platform
    summary: Platform to build
    is_required: true
    value_options:
    - all
    - android
    - ios

- work_dir: $BITRISE_SOURCE_DIR
  opts:
    title: Work dir
    summary: Directory containing the Expo project (app.json)
    is_required: true
