// Code generated by mockery v2.9.4. DO NOT EDIT.

package step

import mock "github.com/stretchr/testify/mock"

// MockEASClient is an autogenerated mock type for the EASClient type
type MockEASClient struct {
	mock.Mock
}

// Build provides a mock function with given fields: platform, options
func (_m *MockEASClient) Build(platform string, options ...string) error {
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = options[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, platform)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, ...string) error); ok {
		r0 = rf(platform, options...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
