// Code generated by mockery v2.9.4. DO NOT EDIT.

package step

import mock "github.com/stretchr/testify/mock"

// MockEASClient is an autogenerated mock type for the EASClient type
type MockEASClient struct {
	mock.Mock
}

// Build provides a mock function with given fields: platform
func (_m *MockEASClient) Build(platform string) error {
	ret := _m.Called(platform)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(platform)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
