// Code generated by mockery v2.9.4. DO NOT EDIT.

package step

import (
	stepconf "github.com/bitrise-io/go-steputils/v2/stepconf"
	mock "github.com/stretchr/testify/mock"
)

// MockEASClientBuilder is an autogenerated mock type for the EASClientBuilder type
type MockEASClientBuilder struct {
	mock.Mock
}

// Build provides a mock function with given fields: token, workDir
func (_m *MockEASClientBuilder) Build(token stepconf.Secret, workDir string) EASClient {
	ret := _m.Called(token, workDir)

	var r0 EASClient
	if rf, ok := ret.Get(0).(func(stepconf.Secret, string) EASClient); ok {
		r0 = rf(token, workDir)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(EASClient)
		}
	}

	return r0
}
